  language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements.txt
  script:
    - python3 -m pytest test/
    - pip install pycodestyle
    - pycodestyle --max-line-length=120 .


